main: zk.JoinQuitPlus.JoinQuitPlus
version: 1.0.0
name: JoinQuitsPlus
author: ZkAleeJoo
api-version: 1.13

commands:
  joinquitplus:
    description: Comando principal del plugin
    aliases:
      - jqp
